file = open("Codingal.txt", "r")
print("First Line..")
print(file.readline())
file.close()

file = open("Codingal.txt", "r")
print("Reading multiple lines..")
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
file.close()

file = open("Codingal.txt", "r")
print("File...")
for line in file:
    print(line)
file.close()